### ISSUE TITLE
Setup fail

### ISSUE THREAD

**Issue by thaiph85** [phamdinhkhanh/vnquant#11]
Hello bạn, tôi setup thì báo lỗi dưới, dù đã cài đủ lib rồi

F:\PROJECT\vnquant-master>python setup.py install
F:\PROJECT\vnquant-master\setup.py:12: DeprecationWarning: Due to possible ambiguity, 'convert()' is deprecated. Use 'convert_file()'  or 'convert_text()'.
  read_md = lambda f: convert(f, 'rst')
See http://johnmacfarlane.net/pandoc/installing.html
for installation options
---------------------------------------------------------------

Traceback (most recent call last):
  File "F:\PROJECT\vnquant-master\setup.py", line 33, in <module>
    long_description=read_md('README.md'),
  File "F:\PROJECT\vnquant-master\setup.py", line 12, in <lambda>
    read_md = lambda f: convert(f, 'rst')
  File "F:\PROJECT\Python3.9\lib\site-packages\pypandoc\__init__.py", line 67, in convert
    return _convert_input(source, format, input_type, to, extra_args=extra_args,
  File "F:\PROJECT\Python3.9\lib\site-packages\pypandoc\__init__.py", line 256, in _convert_input
    _ensure_pandoc_path()
  File "F:\PROJECT\Python3.9\lib\site-packages\pypandoc\__init__.py", line 548, in _ensure_pandoc_path
    raise OSError("No pandoc was found: either install pandoc and add it\n"
OSError: No pandoc was found: either install pandoc and add it
to your PATH or or call pypandoc.download_pandoc(...) or
install pypandoc wheels with included pandoc.

F:\PROJECT\vnquant-master>pip install pypandoc pandoc
Requirement already satisfied: pypandoc in f:\project\python3.9\lib\site-packages (1.5)
Requirement already satisfied: pandoc in f:\project\python3.9\lib\site-packages (1.0.2)
Requirement already satisfied: pip>=8.1.0 in f:\project\python3.9\lib\site-packages (from pypandoc) (21.1.1)
Requirement already satisfied: setuptools in f:\project\python3.9\lib\site-packages (from pypandoc) (56.0.0)
Requirement already satisfied: wheel>=0.25.0 in f:\project\python3.9\lib\site-packages (from pypandoc) (0.36.2)
Requirement already satisfied: ply in f:\project\python3.9\lib\site-packages (from pandoc) (3.11)

**Comment by thaiph85** [comment]
đã fix

**Comment by OppsMarcus** [comment]
> đã fix

Hi thaiph85,
Mình cũng gặp lỗi trên. Bạn chỉ mình cách fix với.
