### ISSUE TITLE
Setup fail - bs4

### ISSUE THREAD

**Issue by thaiph85** [phamdinhkhanh/vnquant#12]
Mình xử lý được lỗi pypandoc rồi, thì giờ lại lòi ra món này

error: Could not find suitable distribution for Requirement.parse('bs4>=4.9.3')

Bs4 thì mới có phiên bản 0.0.1, làm gì có 4.9.3 nhỉ?
https://pypi.org/simple/bs4/

F:\PROJECT\vnquant-master>pip install bs4
Requirement already satisfied: bs4 in f:\project\python3.9\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in f:\project\python3.9\lib\site-packages (from bs4) (4.9.3)
Requirement already satisfied: soupsieve>1.2 in f:\project\python3.9\lib\site-packages (from beautifulsoup4->bs4) (2.2.1)

**Comment by phamdinhkhanh** [comment]
mình đã điều chỉnh version của bs4 rồi bạn nhé. Bạn clone bản mới nhất về sử dụng xem sao.

**Comment by thaiph85** [comment]
Ngon rồi nhé, thanks bạn
