### ISSUE TITLE
sai dữ liệu khi có sự kiện thay đổi giá

### ISSUE THREAD

**Issue by tuansacer** [phamdinhkhanh/vnquant#19]
Dear bạn, 
Ví dụ những mã có sự kiện trả cổ tức hoặc cổ phiếu thưởng -> giá trên biểu đồ sẽ được chia lại nhưng thư viện chưa thể hiện giá mới:

![image](https://user-images.githubusercontent.com/37577474/140480045-c86f1fd2-99a9-4932-97fb-e7c157439a1d.png)

**Comment by phamdinhkhanh** [comment]
Cảm ơn bạn đã chia sẻ. Hiện tại có 2 source có thể sử dụng là VND và CAFE. Bạn cho mình biết câu lệnh bạn sử dụng được ko?

**Comment by Griffs2** [comment]
Mình lấy dữ liệu lấy từ nguồn VND ko điều chỉnh giá. Nguồn Cafef thì có điều chỉnh nhưng toàn bộ mã Upcom bị lỗi ko lấy được dữ liệu

**Comment by pgiaphu** [comment]
Mình cũng mới bị lỗi này hôm nay nhé, lỗi tương tự bạn 2 bạn ở trên

![image](https://user-images.githubusercontent.com/99589333/210402317-04821a61-131b-4ae9-b8b7-56486f1c84ee.png)

**Comment by phamdinhkhanh** [comment]
@tuansacer bạn chạy code dưới đây với `minimal=False` và `data_source='VND'` nhé:
```
loader = dt.DataLoader('PC1', '2021-10-15','2021-11-05', minimal=False, data_source='VND')
df = loader.download()
print(df.loc['2021-11-03'])
```

Kết quả của ngày 03/11/2021 thi bạn lấy cột adjust_close chính là giá điều chỉnh nhé.

```
Attributes        Symbols
code              PC1                   PC1
floor             PC1                  HOSE
basic_price       PC1                  42.6
ceiling_price     PC1                 45.55
floor_price       PC1                 39.65
close             PC1                  41.0
open              PC1                  42.6
high              PC1                  42.9
low               PC1                  40.1
average           PC1                 41.77
adjust_close      PC1                25.836
adjust_open       PC1                26.844
adjust_high       PC1                27.033
adjust_low        PC1                25.269
adjust_average    PC1                26.321
change            PC1                  -1.6
adjust_change     PC1               -1.0082
percent_change    PC1               -3.7559
volume_match      PC1             2899500.0
value_match       PC1        121120815000.0
volume_reconcile  PC1                   0.0
value_reconcile   PC1                   0.0
total_volume      PC1             2899500.0
total_value       PC1        121120815000.0
```

**Comment by phamdinhkhanh** [comment]
@Griffs2 dữ liệu UPCOM bản mới nhất đã hỗ trợ bạn nhé.
https://github.com/phamdinhkhanh/vnquant/issues/22
