### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Duc-Tam-Huynh** [phamdinhkhanh/vnquant#25]
Em cài trên máy local bị lỗi này làm sao để fix vậy anh?
![Loi](https://user-images.githubusercontent.com/68654236/190954733-957af2ef-1550-4848-9c58-ce043f033ea2.PNG)

**Comment by Duc-Tam-Huynh** [comment]
Mình đã fix được lỗi này bằng cách sửa read_md = lambda f: open(f, 'r', encoding='cp437').read() ở hàng 14 trong file setup.py
![image](https://user-images.githubusercontent.com/68654236/192425446-ba67aa21-e5b9-4bdf-b417-5a79fb2e3405.png)

**Comment by skedastically** [comment]
Nên thêm `encoding='utf-8'`  vào line 14 để chỉ rõ cách decode file README.md?

```python
    read_md = lambda f: open(f, 'r', encoding= 'utf-8').read()
```

[Issue liên quan](https://github.com/PythonOT/POT/issues/33)
