### ISSUE TITLE
New method to get stocks data from VNDirect

### ISSUE THREAD

**Issue by nqhung291** [phamdinhkhanh/vnquant#6]
Right now, we can crawl VNDirect's stocks data directly through their new Rest API for faster speed.
This is my function to fetch API
```python
def crawl_one_symbol(symbol, start_date, end_date):
        API_VNDIRECT = 'https://finfo-api.vndirect.com.vn/v4/stock_prices/'
        query = 'code:' + symbol + '~date:gte:' + start_date + '~date:lte:' + end_date
        delta = datetime.strptime(end_date, '%Y-%m-%d') - datetime.strptime(start_date, '%Y-%m-%d')
        params = {
            "sort": "date",
            "size": delta.days + 1,
            "page": 1,
            "q": query
        }
        res = requests.get(API_VNDIRECT, params=params)
        data = res.json()['data']
        return data
```

**Comment by chienpm304** [comment]
> ```python
> 
>             "q": query
> ```
Many thank <3

**Comment by phamdinhkhanh** [comment]
Amazing @nqhung291. Thank you so much!

**Comment by Old-AI-194** [comment]
@nqhung291 
Do you have Rest API for crawling the realltime Bid-Ask price in Derivative PriceBroad of Vndirect ? Tks !!!

**Comment by phamdinhkhanh** [comment]
Hello, Currently we do not have realtime Bid-Ask price in Derivatives
PriceBoard. If you know the API, kindly donate to our project and quant
community.

**Comment by nttams** [comment]
thanks, very helpful
but I can not find any official document for this API. do you know about that?
Or this API is found by dev tools in vndirect site?

**Comment by DoanMinhTruong** [comment]
Can you get VNI ?
