### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by HenryPhan** [phamdinhkhanh/vnquant#8]
import vnquant.DataLoader as web
loader = web.DataLoader('VND', '2018-02-02','2018-04-02')
data = loader.download()
data.head()

ValueError                                Traceback (most recent call last)
<ipython-input-36-a817844cd804> in <module>
      1 import vnquant.DataLoader as web
      2 loader = web.DataLoader('VND', '2018-02-02','2018-04-02')
----> 3 data = loader.download()
      4 data.head()

~/opt/anaconda3/lib/python3.8/site-packages/vnquant-0.0.2-py3.8.egg/vnquant/DataLoader.py in download(self)
     30         else:
     31             loader = DataLoaderCAFE(self.symbols, self.start, self.end)
---> 32             stock_data = loader.download()
     33             # logging.info('Data CAFE: {}'.format(stock_data))
     34 

~/opt/anaconda3/lib/python3.8/site-packages/vnquant-0.0.2-py3.8.egg/vnquant/DataLoader.py in download(self)
    185 
    186         for symbol in symbols:
--> 187             stock_datas.append(self.download_one(symbol))
    188 
    189         data = pd.concat(stock_datas, axis=1)

~/opt/anaconda3/lib/python3.8/site-packages/vnquant-0.0.2-py3.8.egg/vnquant/DataLoader.py in download_one(self, symbol)
    208                 break
    209 
--> 210         stock_data['change_perc1'], stock_data['change_perc2'] = stock_data.change_perc.apply(utils.split_change_col).str
    211         if 'change_perc' in stock_data.columns:
    212             stock_data.pop('change_perc')

ValueError: not enough values to unpack (expected 2, got 0)

**Comment by phamdinhkhanh** [comment]
Có một số mã như VND sẽ bị lỗi mình vẫn chưa fix được.

**Comment by phamdinhkhanh** [comment]
Hiện tại mình đã cập nhật thêm data_source = 'VND' rồi nhé. Bạn có thể sử dụng data source này thay thế cho CAFE nếu mã không clone được.
