### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by HenryPhan** [phamdinhkhanh/vnquant#9]
from vnquant.DataLoader import DataLoader

DataLoader(symbols="VND",
           start="2018-01-10",
           end="2018-02-15",
           data_source="cafe",
           minimal=True)

data = DataLoader.download()

TypeError                                 Traceback (most recent call last)
<ipython-input-50-9633eafb6ac8> in <module>
      7            minimal=True)
      8 
----> 9 data = DataLoader.download()

TypeError: download() missing 1 required positional argument: 'self'

**Comment by phamdinhkhanh** [comment]
Không phải làm như vậy bạn. Mình phải khởi tạo object loader trước, sau đó mới gọi hàm download() từ object này để thu về dataframe. Bạn xem ví dụ bên dưới.

```
import vnquant.DataLoader as dl
loader = dl.DataLoader('VIC', '2018-02-02','2018-04-02', data_source='CAFE', minimal=True)
data = loader.download()
```
